[package]
name = "ralps-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ralps"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
tokio.workspace = true
api = { path = "../libs/api" }
shared = { path = "../libs/shared" }
